site_name: Singing Carrots Docs
site_url: https://singingcarrots.com/docs/    # ← makes MkDocs output sitemap.xml :contentReference[oaicite:0]{index=0}
theme:
  name: material                              # built-in search, dark-mode, tabs :contentReference[oaicite:1]{index=1}
use_directory_urls: true                      # pretty /guide/ URLs :contentReference[oaicite:2]{index=2}
nav:
  - Home: index.md