name: Build & Publish Docs
on:
  push:
    branches: [ main ]
permissions:
  contents: write    # so the action can push to gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - run: pip install mkdocs mkdocs-material

      - run: mkdocs gh-deploy --force --clean --cname docs.singingcarrots.com # builds then pushes to gh-pages :contentReference[oaicite:4]{index=4}